name: Build & Run Docker

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env from Secrets
        run: |
          mkdir -p configs
          cat <<EOF > configs/local.env
          LOGGER_LEVEL=${{ secrets.LOGGER_LEVEL }}
          SERVICE_NAME=${{ secrets.SERVICE_NAME }}
          VERSION=${{ secrets.VERSION }}
          GRPC_PORT=${{ secrets.GRPC_PORT }}
          GRPC_HOST=${{ secrets.GRPC_HOST }}
          HTTP_PORT=${{ secrets.HTTP_PORT }}
          HTTP_HOST=${{ secrets.HTTP_HOST }}
          FILE_STORAGE_PATH=${{ secrets.FILE_STORAGE_PATH }}
          FILE_MAX_SIZE=${{ secrets.FILE_MAX_SIZE }}
          FILE_READ_SIZE=${{ secrets.FILE_READ_SIZE }}
          EOF

      - name: Build Docker image
        run: docker build -t file-service .

      - name: Run Docker container
        run: |
          docker run --rm \
            -p 8080:8080 \
            -p 50051:50051 \
            file-service
