name: Debug Secrets

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (Optional - only if you need code)
        uses: actions/checkout@v4

      - name: Output Secrets (DEBUG ONLY - REMOVE THIS STEP AFTER DEBUGGING)
        run: |
          echo "LOGGER_LEVEL: ${{ secrets.LOGGER_LEVEL }}"
          echo "SERVICE_NAME: ${{ secrets.SERVICE_NAME }}"
          echo "VERSION: ${{ secrets.VERSION }}"
          echo "GRPC_PORT: ${{ secrets.GRPC_PORT }}"
          echo "GRPC_HOST: ${{ secrets.GRPC_HOST }}"
          echo "HTTP_PORT: ${{ secrets.HTTP_PORT }}"
          echo "HTTP_HOST: ${{ secrets.HTTP_HOST }}"
          echo "FILE_STORAGE_PATH: ${{ secrets.FILE_STORAGE_PATH }}"
          echo "FILE_MAX_SIZE: ${{ secrets.FILE_MAX_SIZE }}"
          echo "FILE_READ_SIZE: ${{ secrets.FILE_READ_SIZE }}"

      - name: Output Environment Variables (Optional - if you set secrets as env vars)
        run: |
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
          # Add more environment variables as needed
